services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"        # Porta para acessar via Nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

