name: Run CICD

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Build
        run: |
          cd app  
          go build -ldflags="-w -s" -o main
      - name: Connect To Server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            ./deploy.sh

